apiVersion: v1
kind: Service
metadata:
  labels:
    app: open-flights-app
    env: dev
  name: open-flights-svc
spec:
  # type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    # nodePort: 30000
  selector:
    app: open-flights-app
    env: dev
status:
  loadBalancer: {}
