resources:
- ../../base
  
namePrefix: dev-

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: open-flights-app
      name: open-flights-svc
    spec:
      ports:
      - port: 3000
        protocol: TCP
        targetPort: 3000
        nodePort: 30000
      type: NodePort
     
  target:
    # group: apps
    # version: v1
    kind: Service
    name: open-flights-svc
