resources:
- ../../base

namespace: open-flights-dev
namePrefix: dev-

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    spec:
      type: NodePort
      ports:
      - nodePort: 30000
  target:
    # group: apps
    # version: v1
    kind: Service
    name: open-flights