resources:
- ../../base

namespace: open-flights-dev
namePrefix: dev-

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    # metadata:
    #   name: open-flights-svc
    spec:
      type: NodePort
      ports:
      - port: 3000
        protocol: TCP
        targetPort: 3000
        nodePort: 30000
  target:
    # group: apps
    # version: v1
    kind: Service
    name: open-flights-svc