apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-flights-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: open-flights
    repoURL: git@github.com:hawkinswinja/K8s.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true